// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA63iVRlJPJ96b8Gbps6rRL-6WpFXrV4Lg',
    appId: '1:418222978339:android:2adb131750a3059bbec896',
    messagingSenderId: '418222978339',
    projectId: 'ioweyou-78312',
    databaseURL: 'https://ioweyou-78312.firebaseio.com',
    storageBucket: 'ioweyou-78312.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAESi_t8oC4YOLXQF8KPpVJEPlGdAAmFYg',
    appId: '1:418222978339:ios:5d94f5bfa83588a7bec896',
    messagingSenderId: '418222978339',
    projectId: 'ioweyou-78312',
    databaseURL: 'https://ioweyou-78312.firebaseio.com',
    storageBucket: 'ioweyou-78312.appspot.com',
    iosClientId: '418222978339-rs61j5s27nmb4438phunpttl1ei6e11e.apps.googleusercontent.com',
    iosBundleId: 'com.example.iouV2',
  );
}
